export const UserProfileInitialState = {
  playingRange: {
    lower: 0,
    upper: 0,
  },
  drinkingSmoking: {
    drinks: false,
    smokes: false,
    neither: false,
    noSmokers: false,
    noDrinkers: false,
  },
  musicPrefs: {
    must: false,
    indifferent: false,
    none: false,
  },
  timePrefs: {
    weekendDaytime: false,
    weekendTwilight: false,
    weekdayDaytime: false,
    weekdayTwilight: false,
  },
  _id: "",
  creationTime: "",
  name: "",
  phoneNumber: "",
  gender: "",
  email: "",
  birthday: "",
  handicap: 0,
  courseDescription: "",
  selfDescription: "",
  image: "",
  likes: [],
  dislikes: [],
  matches: [],
  __v: 0,
  stage: "1",
};
