name: MatchPlayUserAPI-dev

on:
  push:
    branches: ["develop"]
  pull_request:
    branches: ["develop"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js 21.x
        uses: actions/setup-node@v3
        with:
          node-version: "21.x"
          cache: "npm"
          cache-dependency-path: "./MatchPlayUserAPI/package-lock.json"

      - name: Install dependencies
        run: npm ci
        working-directory: ./MatchPlayUserAPI

      - name: Create env file
        working-directory: ./MatchPlayUserAPI
        run: |
          touch .env
          echo MONGODB_URI = ${{secrets.MONGODB_URI_DEV}} >> .env
          echo PORT = ${{vars.PORT}} >> .env

      - name: test
        run: npm test
        working-directory: ./MatchPlayUserAPI

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: ./MatchPlayUserAPI
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/matchplay-dev:latest
